# Generated by Django 5.1.5 on 2025-03-08 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_aichatbottable_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('totalamt', models.IntegerField(blank=True, null=True)),
                ('goal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_shows', to='myapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='GoalsTableCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_now', models.IntegerField(blank=True, null=True)),
                ('totalamt', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('goal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='myapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeandExpensesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('wallet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='myapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='WalletAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('wallet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_adds', to='myapp.logintable')),
            ],
        ),
        migrations.RenameModel(
            old_name='IncomeAndExpenceAlertTable',
            new_name='IncomeAndExpenseAlertTable',
        ),
        migrations.DeleteModel(
            name='BillAlertTable',
        ),
        migrations.DeleteModel(
            name='BillsTable',
        ),
        migrations.DeleteModel(
            name='GoalsTable',
        ),
        migrations.DeleteModel(
            name='IncomeandExpencesTable',
        ),
        migrations.DeleteModel(
            name='ReviewTable',
        ),
        migrations.DeleteModel(
            name='StockTable',
        ),
        migrations.RenameField(
            model_name='aichatbottable',
            old_name='recever',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='budgettable',
            old_name='price',
            new_name='price_limit',
        ),
        migrations.RenameField(
            model_name='graphandcharttable',
            old_name='budgetview',
            new_name='budget_view',
        ),
        migrations.RenameField(
            model_name='usertable',
            old_name='dateofbirth',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='usertable',
            old_name='firstname',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='usertable',
            old_name='lastname',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usertable',
            old_name='age',
            new_name='phoneno',
        ),
        migrations.RemoveField(
            model_name='graphandcharttable',
            name='transcactionview',
        ),
        migrations.AddField(
            model_name='budgettable',
            name='budgetname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budgettable',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budgettable',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='myapp.usertable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphandcharttable',
            name='transaction_view',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supporttable',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='myapp.logintable'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='myapp.logintable'),
        ),
        migrations.AddField(
            model_name='incomeandexpensestable',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myapp.usertable'),
        ),
        migrations.AddField(
            model_name='incomeandexpensestable',
            name='wallet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myapp.logintable'),
        ),
    ]
