# Generated by Django 5.1.5 on 2025-03-08 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_goalshow_goalstablecreation_incomeandexpensestable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable'),
            preserve_default=False,
        ),
    ]
