# Generated by Django 5.1.5 on 2025-03-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_wallet_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='WalletAdd',
        ),
    ]
