# Generated by Django 5.1.5 on 2025-03-08 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_wallet_wallet_name_delete_walletadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeandexpensestable',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myapp.logintable'),
        ),
        migrations.AlterField(
            model_name='incomeandexpensestable',
            name='wallet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myapp.wallet'),
        ),
    ]
