# Generated by Django 5.1.5 on 2025-03-08 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_incomeandexpensestable_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomeandexpensestable',
            old_name='userid',
            new_name='LOGINID',
        ),
        migrations.AlterField(
            model_name='incomeandexpensestable',
            name='wallet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionswallet', to='myapp.wallet'),
        ),
    ]
