# Generated by Django 5.1.5 on 2025-03-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_userid_incomeandexpensestable_loginid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
