# Generated by Django 5.1.5 on 2025-03-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_logintable_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintable',
            name='is_active',
        ),
        migrations.AddField(
            model_name='usertable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
