# Generated by Django 5.1.5 on 2025-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_logintable_is_active_usertable_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='budgettable',
            name='date',
        ),
        migrations.RemoveField(
            model_name='budgettable',
            name='description',
        ),
        migrations.RemoveField(
            model_name='budgettable',
            name='userid',
        ),
    ]
