# Generated by Django 5.1.5 on 2025-03-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_budgettable_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_income_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_expence',
        ),
        migrations.RenameField(
            model_name='category_expence',
            old_name='category_name',
            new_name='category_expence_name',
        ),
        migrations.RenameField(
            model_name='incomeandexpensestable',
            old_name='category',
            new_name='Category_expence',
        ),
        migrations.AddField(
            model_name='goalstablecreation',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goaltransactions', to='myapp.logintable'),
        ),
        migrations.AddField(
            model_name='goalstablecreation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category_income'),
        ),
        migrations.AddField(
            model_name='incomeandexpensestable',
            name='Category_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category_income'),
        ),
    ]
