# Generated by Django 5.1.5 on 2025-03-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_category_income_rename_category_category_expence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_expence',
            old_name='category_expence_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category_income',
            old_name='category_income_name',
            new_name='category_name',
        ),
    ]
