# Generated by Django 5.1.5 on 2025-03-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_category_expence_name_category_expence_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettable',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='myapp.usertable'),
            preserve_default=False,
        ),
    ]
