# Generated by Django 5.1.5 on 2025-03-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_goalstablecreation_amount_now_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstablecreation',
            name='goal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
