# Generated by Django 5.1.5 on 2025-03-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_goalstablecreation_goal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalstablecreation',
            name='description',
        ),
    ]
