# Generated by Django 5.1.5 on 2025-03-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_goalstablecreation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstablecreation',
            name='totalamt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
