# Generated by Django 5.1.5 on 2025-03-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_goalstablecreation_totalamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporttable',
            name='support_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
