# Generated by Django 5.1.4 on 2025-01-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_aichatbottable_billalerttable_budgetalerttable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatbottable',
            name='sender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billalerttable',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetalerttable',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goalalerttable',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graphandcharttable',
            name='transcactionview',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomeandexpencealerttable',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewtable',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocktable',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
